### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by gre** [gre/webgltexture-loader#7]
(reminder to myself)

**Comment by serhiipalash** [comment]
@gre what will be in the new version?

Something like this? :)

<img width="1146" alt="screen shot 2018-11-08 at 4 03 29 pm" src="https://user-images.githubusercontent.com/14208343/48203387-10a6a880-e370-11e8-8e35-dd3643001a3a.png">

https://github.com/serhiipalash/webgltexture-loader/commits/master

I was going to create pr later today or tomorrow when test everything on real device.

**Comment by gre** [comment]
just the current master. reminder to myself i need to push current master into npm

**Comment by serhiipalash** [comment]
Hi @gre! Can you please publish new version or `webgltexture-loader-expo`? The current one causes a warning 
<img width="806" alt="screen shot 2018-12-01 at 6 19 47 pm" src="https://user-images.githubusercontent.com/14208343/49330338-b5925b00-f595-11e8-9ca8-eeda70722102.png">
and because of this performance in development is very slow.

Also please check my pr https://github.com/gre/webgltexture-loader/pull/8, it fixes assets resolving in Expo standalone app on Android.

**Comment by gre** [comment]
done. sorry for delay.
